monstruox/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path("clan_form",views.clan_form,name="clan_form"),
    path('user/<str:nickname>/', views.user, name='user'),
    path('friend-request/send/<int:receiver_id>/', views.send_friend_request, name='send_friend_request'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
import os.path

from django.db import models
from django.contrib.auth.models import User
from PIL import Image

from django.db import models
from django.contrib.auth.models import User

class Clan(models.Model):
    name=models.CharField(max_length=72,unique=True)
    motto=models.CharField(max_length=256,unique=True)
    description=models.TextField(null=True,blank=True)
    leader=models.OneToOneField(User,on_delete=models.SET_NULL,null=True,blank=True)
    creation_date=models.DateField(auto_now_add=True)
    level = models.PositiveIntegerField(default=1)
    experience = models.PositiveIntegerField(default=0)
    emblem=models.ImageField(upload_to="emblems/",null=True,blank=True,default="default_emblem.jpg")

    def __str__(self):
        return self.name

class Player(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    nickname=models.CharField(max_length=60,unique=True)
    bio=models.CharField(max_length=256,null=True)
    credits=models.FloatField(default=0.0)
    level=models.PositiveIntegerField(default=1)
    experience=models.PositiveIntegerField(default=0)
    avatar=models.ImageField(upload_to="avatar/",null=True,blank=True,default="default.jpg")
    clan=models.OneToOneField(Clan,on_delete=models.CASCADE,null=True,blank=True)
    friends=models.ManyToManyField("self",symmetrical=True,blank=True)

    def __str__(self):
        return self.nickname

    def add_friend(self,friend):
        self.friends.add(friend)
        friend.friends.add(self)



class FriendRequest(models.Model):
    sender = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='sent_friend_requests')
    receiver = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='received_friend_requests')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender} -> {self.receiver}"

class ClanRequest(models.Model):
    sender = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='sent_clan_requests')
    receiver = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='received_clan_requests')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender} -> {self.receiver} (Clan)"

users/forms.py
import os.path
from django.conf import settings
from django import forms
from .models import Player,Clan


class PlayerForm(forms.ModelForm):
    image_clear = forms.BooleanField(required=False, label="Clear image")

    class Meta:
        model = Player
        fields = ['nickname', 'bio', 'avatar', 'image_clear']
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.cleaned_data.get('image_clear'):
            if instance.avatar and instance.avatar.name != 'default.jpg':
                instance.avatar.delete(save=False)
            instance.avatar = 'default.jpg'
        if commit:
            instance.save()
        return instance

class ClanForm(forms.ModelForm):
    emblem_clear = forms.BooleanField(required=False)

    class Meta:
        model = Clan
        fields = ["name", "motto", "description", "emblem"]
        widgets = {
            # the forms.FileInput removes the current and clear text from ImageField!!!
            'emblem': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

    def clean_description(self):
        description=self.cleaned_data.get("description")
        if len(description.rstrip())>2500:
            raise forms.ValidationError("The description is too long, it can be 2500 characters max")

    def save(self, commit=True):
        instance = super(ClanForm, self).save(commit=False)
        if self.cleaned_data.get('emblem_clear'):
            if instance.emblem and instance.emblem.name != 'default_emblem.jpg':
                instance.emblem.delete(save=False)
            instance.emblem = 'default_emblem.jpg'
        if commit:
            instance.save()
        return instance

users/views.py
import os.path
from django.conf import settings
from django.shortcuts import render,redirect
from django.dispatch import receiver
from django.contrib.auth.decorators import login_required
from .models import Player,Clan,FriendRequest
from django.contrib.auth.models import User
from .forms import PlayerForm,ClanForm
from django.core.exceptions import ObjectDoesNotExist
from PIL import Image
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.db import transaction
def index(request):
    return render(request,"users/index.html")

def profile(request):
    user = request.user
    try:
        player = Player.objects.get(user=user)
    except Player.DoesNotExist:
        player = None

    if request.method == "POST":
        form = PlayerForm(request.POST, request.FILES, instance=player)
        if form.is_valid():
            current_player = form.save(commit=False)
            current_player.user = user  # Ensure the user is set for the new player

            # Check if the nickname already exists for another user
            if Player.objects.filter(nickname=form.cleaned_data.get('nickname')).exclude(user=user).exists():
                form.add_error('nickname', 'This nickname is already taken.')
            else:
                avatar = form.cleaned_data.get("avatar")
                if avatar and not isinstance(avatar, str):
                    avatar_filename = f'{current_player.nickname}{os.path.splitext(avatar.name)[1]}'
                    avatar_path = os.path.join(settings.MEDIA_ROOT, "avatar", avatar_filename)

                    with Image.open(avatar) as image:
                        image.thumbnail((200, 200))
                        if image.format == 'JPEG':
                            image.save(avatar_path, quality=100)
                        elif image.format == 'PNG':
                            image.save(avatar_path, optimize=True)
                        else:
                            image.save(avatar_path)  # For other formats

                    current_player.avatar = f"avatar/{avatar_filename}"

                current_player.save()
                return redirect("index")
    else:
        form = PlayerForm(instance=player)

    return render(request, "users/player_form.html", {"form": form})

@login_required
def clan_form(request):
    user = request.user

    # Get the clan instance if it exists, otherwise None
    clan = Clan.objects.filter(leader=user).first()

    if request.method == "POST":
        form = ClanForm(request.POST, request.FILES, instance=clan)
        if form.is_valid():
            current_clan = form.save(commit=False)

            if form.cleaned_data.get("emblem"):
                emblem = form.cleaned_data.get("emblem")
                emblem_filename = f'{current_clan.name}{os.path.splitext(emblem.name)[1]}'
                emblem_path = os.path.join(settings.MEDIA_ROOT, "emblems", emblem_filename)

                os.makedirs(os.path.dirname(emblem_path), exist_ok=True)

                with Image.open(emblem) as image:
                    image.thumbnail((200, 200))
                    if image.format == 'JPEG':
                        image.save(emblem_path, quality=100)
                    elif image.format == 'PNG':
                        image.save(emblem_path, optimize=True)
                    else:
                        image.save(emblem_path)  # For other formats

                current_clan.emblem = f"emblems/{emblem_filename}"

            if not current_clan.leader:
                current_clan.leader = user

            current_clan.save()
            return redirect("index")
    else:
        form = ClanForm(instance=clan)

    return render(request, "users/clan_form.html", {"form": form})

@login_required
def user(request,nickname):
    player=Player.objects.get(nickname=nickname)
    if user==request.user.player:
        return redirect('profile')
    return render(request,"users/user.html",{"player":player})

@login_required
def send_friend_request(request, receiver_id):
    sender = request.user.player
    receiver = get_object_or_404(Player,id=receiver_id)
    if request.method=="POST":
        if sender!=receiver:
            new_request=FriendRequest(sender=sender,receiver=receiver)
            new_request.save()
            return JsonResponse({"status":"success","message":"Friend request has been sent"})
        else:
            return JsonResponse({"status":"error","message":"You can't send friend request to yourself"})
    return JsonResponse({"status": "failed", "message": "Invalid request method"}, status=405)
@login_required
@transaction.atomic
def accept_friend_request(request,request_id):
    friend_request=get_object_or_404(FriendRequest,id=request_id)
    if request.method=="POST":
        if friend_request.receiver!=request.user.player:
            return JsonResponse({"status": "failed", "message": "You are not authorized to accept this friend request"},status=403)
        if friend_request.receiver!=friend_request.sender:
            friend_request.receiver.add_friend(friend_request.sender)
            friend_request.delete()
            return JsonResponse({"status":"accepted"})
        return JsonResponse({"status":"error","message":"You cant send yourself a friend request"})
    return JsonResponse({"status":"failed"},status=400)

@login_required
@transaction.atomic
def reject_friend_request(request,request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id)
    if request.method == "POST":
        if friend_request.receiver!=request.user.player:
            return JsonResponse({"status": "failed", "message": "You are not authorized to accept this friend request"},status=403)
        friend_request.delete()
        return JsonResponse({"status":"accepted"})
    return JsonResponse({"status": "failed"}, status=400)

users/templates/users/clan_form.html
{% extends 'layouts/box.html' %}

{% load widget_tweaks %}

{% block title %}Clan Form{% endblock %}

{% block content %}
    <h1>Clan Form</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name|add_class:"form-control" }}
            {% if form.name.errors %}
                <div class="alert alert-danger">
                    {% for error in form.name.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.motto.id_for_label }}">{{ form.motto.label }}</label>
            {{ form.motto|add_class:"form-control" }}
            {% if form.motto.errors %}
                <div class="alert alert-danger">
                    {% for error in form.motto.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            {{ form.description|add_class:"form-control" }}
            <small id="description-char-count" class="form-text text-muted">Characters: 0</small>
            {% if form.description.errors %}
                <div class="alert alert-danger">
                    {% for error in form.description.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.emblem.id_for_label }}">{{ form.emblem.label }}</label>
            {{ form.emblem|add_class:"form-control-file" }}
            {% if form.emblem.errors %}
                <div class="alert alert-danger">
                    {% for error in form.emblem.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group form-check">
            {{ form.emblem_clear }}
            <label class="form-check-label" for="{{ form.emblem_clear.id_for_label }}">{{ form.emblem_clear.label }}</label>
            {% if form.emblem_clear.errors %}
                <div class="alert alert-danger">
                    {% for error in form.emblem_clear.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const descriptionField = document.querySelector('#id_description');
            const charCountDisplay = document.getElementById('description-char-count');

            function updateCharCount() {
                const charCount = descriptionField.value.length;
                charCountDisplay.textContent = 'Characters: ' + charCount;
            }

            descriptionField.addEventListener('input', updateCharCount);

            // Initialize character count on page load
            updateCharCount();
        });
    </script>
{% endblock %}

users/templates/users/index.html
{% extends 'layouts/box.html' %}
{% block title %}Monstruox{% endblock %}
{%block content%}
{%endblock%}

users/templates/users/player_form.html
{% extends 'layouts/box.html' %}

{% load widget_tweaks %}

{% block title %}Player Form{% endblock %}

{% block content %}
    <h1>Player Form</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nickname.id_for_label }}">{{ form.nickname.label }}</label>
            {{ form.nickname|add_class:"form-control" }}
            {% if form.nickname.errors %}
                <div class="alert alert-danger">
                    {% for error in form.nickname.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.bio.id_for_label }}">{{ form.bio.label }}</label>
            {{ form.bio|add_class:"form-control" }}
            {% if form.bio.errors %}
                <div class="alert alert-danger">
                    {% for error in form.bio.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.avatar.id_for_label }}">{{ form.avatar.label }}</label>
            {{ form.avatar|add_class:"form-control-file" }}
            {% if form.avatar.errors %}
                <div class="alert alert-danger">
                    {% for error in form.avatar.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="{{ form.image_clear.id_for_label }}">{{ form.image_clear.label }}</label>
            {{ form.image_clear }}
            {% if form.image_clear.errors %}
                <div class="alert alert-danger">
                    {% for error in form.image_clear.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <style>
        .custom-clearable-file-input .clearable-file-input-clear,
        .custom-clearable-file-input .clearable-file-input-initial {
            display: none;
        }
    </style>
{% endblock %}

users/templates/users/user.html
{% extends 'base.html' %}

{% block head_title %}{{ player.nickname }}{% endblock head_title %}

{% block layout %}
<div class="container-fluid px-0">
    <div class="row justify-content-center no-gutters">
        <div class="col-lg-10 px-2 text-center">
            <img src="{{ player.avatar.url }}" alt="Avatar" class="rounded-circle mx-auto d-block mb-3" style="width: 20%; height: auto;">
            <h1>{{ player.nickname }}</h1>
            <div class="d-flex justify-content-center mt-3">
                {% if player not in request.user.player.friends.all %}
                <a id="add-friend-btn" href="#" class="btn btn-outline-primary mr-2" title="Add Friend">
                    <i class="fas fa-user-plus fa-2x"></i>
                </a>
                {% else %}
                <a title="Friends">
                    <i class="bi bi-check-square fa-2x"></i>
                </a>
                {% endif %}
                <a href="#" class="btn btn-outline-primary mr-2" title="Invite to Clan">
                    <i class="fas fa-users-cog fa-2x"></i>
                </a>
                <a href="#" class="btn btn-outline-primary" title="Send Message">
                    <i class="fas fa-envelope fa-2x"></i>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Friend Request</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p id="modal-message"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock layout %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const addFriendBtn = document.getElementById('add-friend-btn');
        if (addFriendBtn) {  // Check if the button exists to avoid errors if it is not rendered
            const userId = {{ request.user.player.id }};
            const playerToAddId = {{ player.id }};  // ID of the player to whom the friend request will be sent

            const protocol = window.location.protocol === 'https:' ? 'wss' : 'ws';
            const friendRequestSocket = new WebSocket(`${protocol}://${window.location.host}/ws/friend_requests/${userId}/`);

            friendRequestSocket.onmessage = function(e) {
                const data = JSON.parse(e.data);
                if (data.type === "friend_request_notification") {
                    if (data.sender_id == data.receiver_id) {
                        showModalMessage("You can't send a friend request to yourself!");
                        return;
                    }
                    alert(`New friend request from ${data.sender_username}`);
                }
            };

            function sendFriendRequest(senderId, receiverId) {
                if (senderId === receiverId) {
                    showModalMessage("You can't send a friend request to yourself!");
                    return;
                }
                friendRequestSocket.send(JSON.stringify({
                    "action": "send_friend_request",
                    "sender_id": senderId,
                    "receiver_id": receiverId
                }));
                showModalMessage("Friend request sent successfully!");
            }

            function showModalMessage(message) {
                document.getElementById('modal-message').textContent = message;
                $('#myModal').modal('show');
            }

            addFriendBtn.addEventListener('click', function(event) {
                event.preventDefault();
                sendFriendRequest(userId, playerToAddId);
            });
        }
    });
</script>
{% endblock scripts %}